config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#destroy'
  post "/items/booking/:id(.:format)", to: 'bookings#create', as: "create_booking"
  get "/booking/detail/:id", to: "bookings#show", as: "booking"
  post "/items/search/search_tmp", to: "items#search_tmp", as:"search_tmp"
  get "/items/search/:key", to: "items#search", as:"search"
  get "user/management", to:"users#management", as:"management"
  post "user/management/confirm", to:"bookings#validate_booking_confirm", as:"validate_booking_confirm"
  post "user/management/confirm/check", to:"bookings#validate_booking", as:"validate_booking"
  root :to => 'top#landing'
  get "/question", to:"application#question_new", as:"question_new"
  post "/question", to:"application#question_create", as:"question_create"
  get "/usage", to:"application#show_usage", as:"show_usage"

  resources :users
  resources :items do
    resources :comments
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    validates :to_email, presence: true, allow_blank: false
    validates :from_email, presence: true, allow_blank: false
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 3, message: "too short"}
  validates :body, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true
  has_one :item
end

app/models/user_item.rb
class UserItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper


  def question_new
    render "layouts/question_new"
  end

  def show_usage
    render "layouts/show_usage"
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @booking = Booking.new(booking_params)
    @booking.serial = SecureRandom.hex(5)
    if @booking.save
      GiftMailer.send_gift(@booking).deliver
      GiftMailer.send_receipt(@booking).deliver
      redirect_to booking_path(@booking.id)
    else
      redirect_to(item_path(@booking.item_id))
      #render plain: @item.errors.inspect
    end
  end
  
  def show
    @booking = Booking.find(params[:id])
  end
  
  def validate_booking_confirm
    @booking = Booking.find(params[:booking_id])
    render 'users/validate_booking_confirm.html.erb'
  end
  
  
  def validate_booking
    if current_user.authenticate(params[:booking_validation][:password])
      @booking = Booking.find(params[:booking_validation][:booking_id])
      if @booking.serial == params[:booking_validation][:serial] 
        @booking.validation = true 
        @booking.save
      end
    end
    redirect_to(management_path)
  end
  
  
  private 
    def booking_params
      params.require(:booking).permit(:to_name, :gift_type, :message, :delivery_method, :to_email, :from_name, :from_email, :item_id)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @item = Item.find(params[:item_id])
    @item.comments.create(comment_params)
    redirect_to item_path(@item)
  end
  
  def destroy
    @item = Item.find(params[:item_id])
    @comment = @item.comments.find(params[:id])
    @comment.destroy
    redirect_to item_path(@item)
  end

  
  
  private 
    def comment_params
      params.require(:comment).permit(:about)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all.order(created_at:"desc")
  end
  
  def new
    @item = Item.new
  end
  
  def show
    @item = Item.find(params[:id])
    @booking = Booking.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      #@user = current_user
      #@user.item_id = @item.id
      #@user.save
      redirect_to item_path(@item.id)
    else
      render "new"
      #render plain: @item.errors.inspect
    end
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render "edit"
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end
  
  def search_tmp
    key_str = params[:search][:key]
    keyAry = key_str.split(" ")
    key_join_plus = keyAry.join("+")
    redirect_to search_path(key_join_plus)
  end
  
  def search
    key_str = params[:key]
    keyAry = key_str.split("+")
    @items = []
    tmparry=[]
    for key in keyAry do
      tmp_match = Item.where("title like '%" + key + "%'")
      if tmp_match
        for tmp in tmp_match do
          tmparry << tmp.id
        end
      end
    end
    @items = Item.find(tmparry)
  end


  private 
    def item_params
      params.require(:item).permit(:title, :body, :location, :price, :reputation, :image)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(name:params[:session][:name])
    if !!user && user.authenticate(params[:session][:password])
      flash.now[:danger] = "welcome #{user.name}"
      log_in(user)
      redirect_to user_path(user.id)
    else
      flash[:danger] = "invalit input"
      render "new"
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end


end

app/controllers/top_controller.rb
class TopController < ApplicationController
def landing
end

def question_mail
end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at:"desc")
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render "new"
      #render plain: @item.errors.inspect
    end
  end
  
  def edit
    @item = item.find(params[:id])
  end
  
  def update
    @item = item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render "edit"
    end
  end
  
  def destroy
    @item = item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end


  def management
  end

  private 
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper




end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/email_helper.rb
module EmailHelper
  def email_image_tag(image, options = {})
    image_tag email_image_url(image), options
  end

  def email_image_url(image)
    attachments[image] = File.read Rails.root.join("app/assets/images/#{image}")
    attachments[image].url
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user=nil
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/show.html.erb
<div class="show-booking">
<div class="row">
  <h2 style="padding: 20px;">ギフトが送信されました！</h2>
  <div class="col-md-6">
<p>発行ギフトの詳細</p>
<ul class="booking-detail">
  <h3>相手のお名前</h3>
  <li><%= @booking.to_name %></li>
  <h3>ギフトの種類</h3>
  <li><%= @booking.gift_type %></li>
  <h3>ひと言メッセージ</h3>
  <li><%= @booking.message %></li>
  <h3>お届け方法</h3>
  <li><%= @booking.delivery_method %></li>
  <h3>お相手のメールアドレス</h3>
  <li><%= @booking.to_email %></li>
  <h3>差出人のお名前</h3>
  <li><%= @booking.from_name %></li>
  <h3>差出人のメールアドレス</h3>
  <li><%= @booking.from_email %></li>
</ul>
</div>
<div class="col-md-6">
  <h3>ギフトカード</h3>
  <p>*送付されるギフトカードは現在準備中です。</p>
  <p>以下のカードはサンプルです。</p>
<%= image_tag "sample2.png" , :class => "sample-booking"%>
</div>

</div>
<br />
  <%= button_to 'ホームに戻る', items_path, method: :get, :class => "btn btn-info" %>

</div>

app/views/items/_booking_error.html.erb
<% if @item.errors.any? %>
  <% @item.errors.messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

app/views/items/_booking_form.html.erb
<div class="position-booking">
  <%= form_for @booking, url: create_booking_path  do |f| %>
    <div class="row">
      <div class="col-md-6">
        <h3>相手のお名前</h3>
        <%= f.text_field :to_name, class: "form-control" %>
        <h3>ギフトの種類</h3>
        <%= f.select :gift_type, [["1000", 1000], ["2000",2000], ["3000",3000], ["4000",4000], ["5000",5000],], {}, {class:"form-control"} %>
      </div>
      <div class="col-md-6">
        <h3>ひと言メッセージ</h3>
        <%= f.text_area :message, placeholder: "例）いつもありがとう！この店のパスタは最高だよ！", class: "form-control" %>
      </div>
    </div>
  
    <hr>
  
  <div class="row">
    <div class="col-md-6">
      <h3>お届け方法</h3>
      <%= f.select :delivery_method, 
      [["メール", 1], ["メール(後日)(準備中)",2], ["カードの郵便(準備中)",3]],
      {selected: 1, disabled: [2,3] }, {class:"form-control"} %>
    </div>
    <div class="col-md-6">
      <h3>お相手のメールアドレス</h3>
      <%= f.email_field :to_email, class: "form-control" %>
    </div>
  </div>  
    
    <hr>
    
  <div class="row">
    <div class="col-md-6">
      <h3>差出人のお名前</h3>
      <%= f.text_field :from_name, class: "form-control" %>
    </div>
    <div class="col-md-6">
      <h3>差出人のメールアドレス</h3>
      <%= f.email_field :from_email, class: "form-control" %>
    </div>
  </div>  
    
    <%= f.hidden_field :item_id, :value => @item.id %>
  
    <hr>
  
    <%= f.submit "ギフトを作成！" , :class =>  "btn btn-primary position-button" %>
  <% end %>

</div>

app/views/items/_comment_form.html.erb
<div class="comment bg-danger">
  <p>コメント</p>
  <% if @item.comments.any? %>
    <% @item.comments.each do |comment|%>
      <%= comment.about %>
      <%= link_to "[x]", item_comment_path(@item.id,comment.id), 
      method: :delete, data: {confirm: "sure?"} %>
  
    <%end%>
  <%end%>
  
  <%= form_for([@item, @item.comments.build]) do |f| %>
   <%= f.text_field :about %>
   <p>
     <%= f.submit "コメント送信" %>
   </p>
 </div>
 
<% end %>

app/views/items/_header_search.html.erb
<div class="item-search">
  <%= image_tag "searchback.jpg" %>
  <div class="message">
  <p>お気に入りのレストランを探す</p>
  <br />
  <%= render "layouts/search_pertial"%>
  </div>
</div>

app/views/items/_item_error.html.erb
<% if @item.errors.any? %>
  <% @item.errors.messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

app/views/items/_item_form.html.erb
<%= form_for @item do |f| %>
  
  <div class="row">
    <div class="col-md-6">
  <h3>レストランの名前</h3>
  <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="col-md-6">
  <h3>住所</h3>
  <%= f.text_field :location, class: "form-control"  %>
    </div>
  </div>  
  <div class="row">
    <div  class="col-md-6">
  <h3>レストランの詳細</h3>
  <%= f.text_area :body, placeholder: "例）おすすめの料理、雰囲気など", class: "form-control "  %>
    </div>
    <div class="col-md-6">
  <h3>平均的な使用金額</h3>
  <%= f.select :price, [["$(~1000)", 1], ["$$(~2000)",2], ["$$$(~5000)",3], ["$$$$(~10000)",4], ["$$$$$(10000~)",5]] ,{},{class:"form-control"} %>
  </br>
  
  <h3>画像</h3>
  <%= f.file_field :image %>
  </div>
  </div>

<br><hr><hr>
  <%= f.submit :class =>  "btn btn-primary position-button" %>
<% end %>

  <h3></h3>

<%
=begin
%>
  <h3>reputation</h3>
  <%= f.select :reputation, [["1", 1], ["2",2], ["3",3], ["4",4], ["5",5]] ,{},{class:"form-control"} %>
<%
=end
%>

app/views/items/_item_summary.html.erb
<div class="summary">
      <h2><%= @item.title %></h2>
      <p><%= (("★"*@item.reputation)+"☆"*5).slice(0..4) || "評価はまだありません" %></p>
      <p><%= @item.location || "住所未登録" %> | <%= "$"*@item.price || "価格未登録" %></p>
<div class="container color-item-summary">
  <div class="position-image">
      <p><%= image_tag @item.image, :class => "booking_item_img position-item-summary" %></p>
  </div>
</div>
  </div>
</div>

app/views/items/_items_index.html.erb
# coding: utf-8

<div class="padding-items">
  <table border="1" class="item-table">
  <% if (items.length==0) then %>  
   <tr><td>
    <h3>一致なし</h3>
   </tr></td>
  <% else %>
    <% items.each do |item| %>
      <tr><td>
        <div class="item">
          <div class="row">
            <div class="col-md-2 ">
              <%= link_to image_tag((item.image), class:"thumnail-item"), item_path(item.id) %>
            </div>
            <div class="col-md-4">
            <%= link_to item.title, item_path(item.id) %>
            <br />
            <p style="display: inline;"><%= (("★"*(item.reputation || 0))+"☆"*5).slice(0..4) || "評価なし"%></p>
            <p style="display: inline;"> || </p>
            <p style="display: inline;"><%= "$"*(item.price || 1) %></p>
            <br>
            <p><%= item.location %></p>
            <%= button_to 'check', item_path(item.id), method: :get, :class => "btn btn-info" %>
            </div>
            <div class="col-md-6">
              <%= item.body %>
            </div>
          </div>
        </div>
      </td></tr>
    <% end %>
  <% end %>
  </table>
</div>

app/views/items/edit.html.erb
<p>"edit item"</p>
<%= render "item_form"%>

app/views/items/index.html.erb
<% content_for :content_header do %>
  <%= render "header_search"%>
<% end %>

<%= render :partial => "items_index", :locals => {items: @items} %>

app/views/items/new.html.erb
<p>"create new item"</p>
<%= render "item_error"%>
<div class="position-item-create">
<%= render "item_form"%>
</div>

app/views/items/search.html.erb
<% content_for :content_header do %>
  <%= render "header_search"%>
<% end %>

<%= render :partial => "items_index", :locals => {items: @items} %>

app/views/items/show.html.erb
<% content_for :content_header do %>
 <%= render "item_summary"%>
<% end %>


<!-- gift form -->
<div class="gift-form">
<%= render "booking_form"%>
</div>

<br>

<!-- commnet -->
<!--<%= render "comment_form"%>-->

app/views/top/landing.html.erb
<% content_for :content_header do %>

  <div class="background">
    <%= image_tag "landing/top/img_present.jpg" %>
    <div class="message">
    <p>あなたの好きなレストランをプレゼントしよう</p>
    <br/>
    <%= button_to 'ギフトを選ぶ', items_path, method: :get, :class => "btn btn-info" %>
    <%= button_to 'サンプルを見る', show_usage_path, method: :get, :class => "btn btn-default" %>
  </div>
  </div>
  
  <div class="landing_function">
      <h1 style="display:inline">service ticketでできること</h1>
<!--    <p align="right">*もっと詳しい機能は<%= link_to "こちら", url:"#" %></p> -->
    <div class="row">
      <div class="col-md-4">
        <%= image_tag "landing/function/gift.png" %>
        <h4>全く新しくて特別なプレゼント</h4>
        <p>あなたの好きなレストランへの招待券をプレゼントすることができます。あなたのセンス光る特別なプレゼントです。</p>
      </div>
      <div class="col-md-4">
        <%= image_tag "landing/function/request.png" %>
        <h4>憧れのお店をおねだり</h4>
        <p>招待されたいレストランをリクエストすることができます。自分では普段行けないお店もお願いできちゃうかも</p>
      </div>
      <div class="col-md-4">
        <%= image_tag "landing/function/online.png" %>
        <h4>手軽で簡単プレゼント・利用</h4>
        <p>招待券の購入、配達、利用はすべてオンラインで手軽に行えます。お互いの住所を公開する必要もありません！お会計もお財布いらず</p>
      </div>
    </div>
  </div>
  
  <div class="landing_process">
    <h1 style="display:inline">service ticketの使い方</h1>
<!--    <p align="right">*もっと詳しい仕組みは<%= link_to "こちら", url:"#" %></p>-->
    <div class="row">
      <div class="col-md-4">
        <%= image_tag "landing/process/search.png" %>
        <h4>1. プレゼントしたいレストランを選ぶ</h4>
        <p>あなたのお気に入りのレストランをプレゼントして、友達にも楽しんでもらいましょう。プレゼントしたい値段は選ぶことができます。</p>
      </div>
      <div class="col-md-4">
        <%= image_tag "landing/process/send.png" %>
        <h4>2. メッセージと一緒に送る</h4>
        <p>メール、Facebook、twitter、LINEでメッセージと一緒に招待状を送ろう！</p>
      </div>
      <div class="col-md-4">
        <%= image_tag "landing/process/eat.png" %>
        <h4>3. 友達のおすすめをタダで楽しむ！</h4>
        <p>もらった招待状を提示して、友達おすすめのレストランでタダでご飯を食べよう！</p>
      </div>
    </div>
  </div>




<!--ペルソナ-->
<!--一段目-->
  <div class="landing_persona">
    <div class="row">
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-3">
        <%= image_tag "landing/persona/giver1.png" %>
          </div>
          <div class="col-md-9">
            <h3>[送る]後輩に焼肉のプレゼントを</h3>
            <p>
              24歳　男性<br />
              サラリーマン<br />
              <br />
              学生時代は体育会系に所属して後輩によくご飯を奢っていたけど、
              最近はなにもしてやれていないな。
              そういえばあいつら、週末の試合頑張ったみたいだし
              Service ticketでお気に入りの焼肉おごってやるか
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-3">
        <%= image_tag "landing/persona/giver2.png" %>
          </div>
          <div class="col-md-9">  
          <h3>[送る]お隣にケーキでいつものお礼を</h3>
          <p>
            35歳　女性<br />
            主婦<br />
            <br />
            お隣さんにはいつもお世話になっているからお返しがしたいわ。
            ケーキが好きって言っていたし、service ticketで新しくできたケーキ屋さんの商品券を送ろうかしら
          </p>
          </div>
        </div>
      </div>
    </div>
<!-- 二段目 -->
    <div class="row">
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-3">
        <%= image_tag "landing/persona/receiver.png" %>
          </div>
          <div class="col-md-9">
            <h3>[もらう]ラーメン屋のプレゼントを友達にリクエスト</h3>
            <p>
              23歳　男性<br />
              大学院生<br />
              <br />
              誕生日プレゼントはせっかくなら欲しいものをもらいたいな。
              小説とリュックと、行きたかったラーメン屋のservice ticketを
              ウィッシュリストでFacebookに公開しておこう
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-3">
        <%= image_tag "landing/persona/owner.png" %>
          </div>
          <div class="col-md-9">
          <h3>[参加する]ファンの広報活動を支援、新規優良顧客獲得</h3>
          <p>
            40歳　男性<br />
            シェフ <br />
            <br />
            リピートしてくれるお客さんはいるんだけど、どうも新規獲得が弱いな。
            クーポンを出しても一度限りのお客が多いし、
            ファンになってリピートしてくれるお客さんが増えたらうれしいのに。
            Service ticket ならお客さん同士の招待だから好みを踏まえたいい宣伝かも
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  
<!-- merit -->
  <div class="landing_merit">
    <h2>こんなに便利！</h2>
    <div class="btn-group" data-toggle="buttons">
    <label class="btn btn-default active"><input type="radio" name="landing_merit_options" id="option_giver_receiver" autocomplete="off" value=0 checked="checked">送る人、もらう人</label>
    <label class="btn btn-default"> <input type="radio" name="landing_merit_options" id="option_owner" autocomplete="off" value=1>お店の人</label>
    </div>

<!-- 送る人、もらう人 --->
    <div class="landing_merit_giver_receiver">
      <h3>～送る人、もらう人～</h3>
      <ul>
        <div class="row">
        <div class="col-md-6">
        <li>
          <p>アプリで簡単操作。すぐにプレゼントできます！
          <%= image_tag "landing/merit/phone.png" %></p>
        </li>
        <li>
          <p>距離や忙しさから会えない場合も気持ちを伝えられます！
          <%= image_tag "landing/merit/hart.png" %></p>
        </li>
        <li>
          <p>住所を知らせなくても利用できます！
          <%= image_tag "landing/merit/lock.png" %></p>
        </li>
        </div>
        <div class="col-md-6"> 
        <li>
          <p>好きなレストランをプレゼントする唯一の方法！
          <%= image_tag "landing/merit/present.png" %></p>
        </li>
        <li>
          <p>プレゼントだけでなく、気になるレストランをリクエストできます！
          <%= image_tag "landing/merit/list.png" %></p>
        </li>
        <li>
          <p>会員登録、利用、すべて手数料ゼロ！
          <%= image_tag "landing/merit/ok.png" %></p>
        </li>
        </div>
        </div>
      </ul>
    </div>
  
<!-- お店 -->
    <div class="landing_merit_owner">
      <h3>～参加するお店～</h3>
      <ul>
        <div class="row">
          <div class="col-md-6">
        <li>
          <p>ギフト券発行によりお店のファンの広報活動を支援できます！
          <%= image_tag "landing/merit/speak.png" %></p>
        </li>
        <li>
          <p>利用者情報を蓄積してファンに恩返しもできます！
          <%= image_tag "landing/merit/database.png" %></p>
        </li>
        <li>
          <p>顧客同士の招待なのでお店の雰囲気にあった新規顧客を獲得できます！
          <%= image_tag "landing/merit/shakehands.png" %></p>
        </li>
        </div>
        <div class="col-md-6">
        <li>
          <p>複数人来店&併売も見込めます！
          <%= image_tag "landing/merit/network.png" %></p>
        </li>
        <li>
          <p>掲載無料、取引手数料有なのでお店の成長がサービスの成長に。<br />損させません！
          <%= image_tag "landing/merit/graph.png" %></p>
        </li>
        </div>
        </div>
      </ul>
    </div>
  </div> 

  <div class="background">
    <%= image_tag "landing/bottom/landing_bottom.jpg" %>
    <div class="message">
    <p>あなたの好きなレストランをプレゼントしよう</p>
    <br/>
    <%= button_to 'ギフトを選ぶ', items_path, method: :get, :class => "btn btn-info" %>
    <%= button_to 'サンプルを見る', show_usage_path, method: :get, :class => "btn btn-default" %>
  </div>
</div>



<!--なんでassets/jsだと動かないんだ。だれか助けて-->
<script>
$('input[name="landing_merit_options"]').change( function(){
    if ($('input[name="landing_merit_options"]:checked').val() == 0) {
      $(".landing_merit_giver_receiver").show();
      $(".landing_merit_owner").hide();
    }else if($('input[name="landing_merit_options"]:checked').val() == 1){
      $(".landing_merit_giver_receiver").hide();
      $(".landing_merit_owner").show();
    }
});
</script>

<% end %>

app/views/users/_guide.html.erb
<ul>
  <li>管理 --- ギフトの管理</li>
  <li>お店を登録する --- あなたのお店を登録する</li>
</ul>

app/views/users/_user_error.html.erb
<% if @user.errors.any? %>
  <% @user.errors.messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

app/views/users/_userform.html.erb
<div class="user-form">
<%= form_for @user do |f| %>
  <h3>ログインID</h3>
  <%= f.text_field :name,  class: "form-control" %>
  <h3>メールアドレス</h3>
  <%= f.email_field :email, class: "form-control" %>
  <h3>電話番号</h3>
  <%= f.text_field :number, class: "form-control"%>
  <h3>パスワード</h3>
  <%= f.password_field :password, class: "form-control" %>
  <h3>パスワード確認</h3>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <br />
  <p>*プロトタイプ版につき、登録を受け付けておりません。</p>
  <p>興味のある方は<%= link_to "こちらへご連絡ください", question_new_path%></p>
  <%= f.submit :class =>  "btn btn-primary position-button", :disabled => true %>
<% end %>
</div>

app/views/users/index.html.erb
<%= link_to "create new user", new_user_path %>
<%= link_to "login", login_path %>


<ul>
  <% @users.each do |user| %>
    <li>
        <%= link_to user.name, user_path(user.id) %>
        <%= link_to "[edit]", edit_item_path(user.id) %>
        <%= link_to "[x]", item_path(user.id), 
        method: :delete, data: {confirm: "sure?"} %>
    </li>
  <% end %>
</ul>

app/views/users/management.html.erb
<h1>Hello <%= current_user.name %> </h1>
<br/>

<% item = Item.find_by(user_id: current_user.id) %>
<% if item %>
  <h3>店名: <%= item.title %></h3>
  <% bookings = Booking.where(item_id: item.id) %>
  <% if bookings %>
      <table class="table table-striped">
        <tr>
          <th>ID</th>
          <th>送り主</th>
          <th>ギフトの種類</th>
          <th>使用状況</th>
        </tr>
    <% bookings.each do |booking| %>
        <tr>
          <td><%= booking.id %></td>
          <td><%= booking.to_name %></td>
          <td><%= booking.gift_type %></td>
          <% if booking.validation == false %>
            <td><%= button_to '使用', {:controller => "bookings", :action => "validate_booking_confirm", :booking_id => booking.id}, method: :post, :class =>  "btn btn-primary" %></td>
          <% else %>
            <td>使用済み</td>
          <% end %>
        </tr>
    <% end %>
      </table>
  <% else %>
  <p>ギフトはまだ発行されていません</p>
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class="padding-form">
  <p>新規利用者登録</p>
  <%= render "user_error"%>
  <%= render "userform"%>
</div>

app/views/users/show.html.erb
<h1> <%= @user.name %>さん　service ticketへようこそ</h1>
<h3>利用ガイド</h3>
<%= render "guide" %>

  <%= button_to 'ホームに戻る', items_path, method: :get, :class => "btn btn-info message" %>

app/views/users/validate_booking_confirm.html.erb
<p>ギフトの詳細</p>
<ul>
  <li><%= @booking.to_name %></li>
  <li><%= @booking.gift_type %></li>
  <li><%= @booking.message %></li>
  <li><%= @booking.delivery_method %></li>
  <li><%= @booking.to_email %></li>
  <li><%= @booking.from_name %></li>
  <li><%= @booking.from_email %></li>
  <li><%= @booking.serial %></li>
</ul>

<h3>このギフトを使用済みにしてよろしいですか</h3>
<%= form_for(:booking_validation, url: validate_booking_path, method: :post) do |f| %>
  <h3>ギフトのシリアル番号</h3>
  <%= f.text_field :serial, class: "form-control" %>
  <h3>あなたのパスワード</h3>
  <%= f.password_field :password, class: "form-control" %>
  <br/>
  
  <%= f.hidden_field :booking_id, :value => @booking.id %>

  
  <%= f.submit "使用", :class =>  "btn btn-primary form-control" %>
<% end %>
<%= link_to "ホームへ戻る", items_path%>