config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#destroy'
  post "/items/booking/:id(.:format)", to: 'bookings#create', as: "create_booking"
  get "/booking/detail/:id", to: "bookings#show", as: "booking"
  post "/items/search/search_tmp", to: "items#search_tmp", as:"search_tmp"
  get "/items/search/:key", to: "items#search", as:"search"
  get "user/management", to:"users#management", as:"management"
  post "user/management/confirm", to:"bookings#validate_booking_confirm", as:"validate_booking_confirm"
  post "user/management/confirm/check", to:"bookings#validate_booking", as:"validate_booking"
  root :to => 'top#landing'
  get "/question", to:"application#question_new", as:"question_new"
  post "/question", to:"application#question_create", as:"question_create"
  get "/usage", to:"application#show_usage", as:"show_usage"

  resources :users
  resources :items do
    resources :comments
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    validates :to_email, presence: true, allow_blank: false
    validates :from_email, presence: true, allow_blank: false
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 3, message: "too short"}
  validates :body, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true
  has_one :item
end

app/models/user_item.rb
class UserItem < ApplicationRecord
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @booking = Booking.new(booking_params)
    @booking.serial = SecureRandom.hex(5)
    if @booking.save
      GiftMailer.send_gift(@booking).deliver
      GiftMailer.send_receipt(@booking).deliver
      redirect_to booking_path(@booking.id)
    else
      redirect_to(item_path(@booking.item_id))
      #render plain: @item.errors.inspect
    end
  end
  
  def show
    @booking = Booking.find(params[:id])
  end
  
  def validate_booking_confirm
    @booking = Booking.find(params[:booking_id])
    render 'users/validate_booking_confirm.html.erb'
  end
  
  
  def validate_booking
    if current_user.authenticate(params[:booking_validation][:password])
      @booking = Booking.find(params[:booking_validation][:booking_id])
      if @booking.serial == params[:booking_validation][:serial] 
        @booking.validation = true 
        @booking.save
      end
    end
    redirect_to(management_path)
  end
  
  
  private 
    def booking_params
      params.require(:booking).permit(:to_name, :gift_type, :message, :delivery_method, :to_email, :from_name, :from_email, :item_id)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @item = Item.find(params[:item_id])
    @item.comments.create(comment_params)
    redirect_to item_path(@item)
  end
  
  def destroy
    @item = Item.find(params[:item_id])
    @comment = @item.comments.find(params[:id])
    @comment.destroy
    redirect_to item_path(@item)
  end

  
  
  private 
    def comment_params
      params.require(:comment).permit(:about)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all.order(created_at:"desc")
  end
  
  def new
    @item = Item.new
  end
  
  def show
    @item = Item.find(params[:id])
    @booking = Booking.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      #@user = current_user
      #@user.item_id = @item.id
      #@user.save
      redirect_to item_path(@item.id)
    else
      render "new"
      #render plain: @item.errors.inspect
    end
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render "edit"
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end
  
  def search_tmp
    key_str = params[:search][:key]
    keyAry = key_str.split(" ")
    key_join_plus = keyAry.join("+")
    redirect_to search_path(key_join_plus)
  end
  
  def search
    key_str = params[:key]
    keyAry = key_str.split("+")
    @items = []
    tmparry=[]
    for key in keyAry do
      tmp_match = Item.where("title like '%" + key + "%'")
      if tmp_match
        for tmp in tmp_match do
          tmparry << tmp.id
        end
      end
    end
    @items = Item.find(tmparry)
  end


  private 
    def item_params
      params.require(:item).permit(:title, :body, :location, :price, :reputation, :image)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(name:params[:session][:name])
    if !!user && user.authenticate(params[:session][:password])
      flash.now[:danger] = "welcome #{user.name}"
      log_in(user)
      redirect_to user_path(user.id)
    else
      flash[:danger] = "invalit input"
      render "new"
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end


end

app/controllers/top_controller.rb
class TopController < ApplicationController
def landing
end

def question_mail
end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at:"desc")
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render "new"
      #render plain: @item.errors.inspect
    end
  end
  
  def edit
    @item = item.find(params[:id])
  end
  
  def update
    @item = item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render "edit"
    end
  end
  
  def destroy
    @item = item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end


  def management
  end

  private 
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper




end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/email_helper.rb
module EmailHelper
  def email_image_tag(image, options = {})
    image_tag email_image_url(image), options
  end

  def email_image_url(image)
    attachments[image] = File.read Rails.root.join("app/assets/images/#{image}")
    attachments[image].url
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user=nil
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header_dev.html.erb
<% if logged_in? %>
  <p><%= link_to "プロファイル", user_path(current_user) %></p>
  <p><%= link_to "ログアウト", logout_path, method: :delete %></p>
<% else %>
  <p><%= link_to "ログイン", login_path %></p>
<% end %>

<% if logged_in? %>
<%= link_to "お店を登録する", new_item_path %>
<% end %>

      <%= link_to "ユーザー一覧", users_path %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

app/views/layouts/_header_menu.html.erb
<%
=begin
%>

<% if logged_in? %>
  <%= link_to " お店を登録する |", new_item_path %>
  <%= link_to " 管理 |", management_path %>
  <%= link_to " ログアウト |", logout_path, method: :delete %>
<% else %>
  <%= link_to " ログイン |", login_path %>
<% end %>



<span class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
  開発用  
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to "ユーザー一覧", users_path %></li>
  </ul>
</span>

<%
=end
%>

app/views/layouts/_search_pertial.html.erb
<%= form_for(:search, url: search_tmp_path, html: {class: 'search-form'}) do |f| %>
  <div class="row">
    <div class="col-md-9">
      <%= f.text_field :key, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.submit "検索", :class =>  "btn btn-primary form-control" %>
    </div>
  </div>
<% end %>


<%
=begin
%>
<%= form_for(:search, url: search_tmp_path) do |f| %>
<%= form_for(@foo, :url => {:controller => :items, :action => :search_tmp}) do |f| %>
<%
=end
%>

app/views/layouts/_tmp_notification.html.erb
<p class="tmp-notification">
<strong>プロトタイプバージョン</strong>です。
先輩にタダ飯を奢ってもらいたい方、ちょっと特別なプレゼントを贈りたい方、お店のファンの自由な活動を支援したい店主さん、このサービス実現に向けて応援してくれませんか？
サービスに興味のある方、参加したい方、質問のある方、プロジェクトの運営に参加したい方、ぜひ<%= link_to "こちらへご連絡ください", question_new_path%>。**1分で終わる<%= link_to "アンケートにご協力いただけませんか？","https://docs.google.com/forms/d/e/1FAIpQLSfjfErJ5DnhGchCoiX20bhvBCzn0tyPe72d9ca-gWLJ8pR4Ww/viewform?usp=sf_link"%>**
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class="main">

    <%= render "layouts/tmp_notification" %>


    <div class="header-top">  
      <%= link_to image_tag("logo.jpg", class:"logo"), root_path %>
      <div class="pull-right">
        <%= render "layouts/header_menu"%>
      </div>

    <!-- flash -->      
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    </div>
      
      <%= yield :content_header%>
  </header>
  <body class="main">
    <div class="container bg-white padding-content" >
      <%= yield %>
    </div>
  <% if !(logged_in?) %>  
    <%= link_to "*店主様　お店を登録しませんか", new_user_path %>
  <% end %>
  </body>
  </div>
</html>

app/views/layouts/question_new.html.erb
<div class="question-form">
<p>こちらは簡易問い合わせ画面です。現在問い合わせ画面を作成中です。</p>

<p>連絡先は　taiga518(アット)gmail.com　です</p>
<p>*(アット)を@に変更してご連絡ください</p>
<p>または、 Line:  http://line.me/ti/p/I3YKeL7Rtv <br />
FB:  http://facebook.com/taiga518<br />
Twitter(peing):https://peing.net/taiga518_biz<br />
TEL: 07026324144<br />
</p>
<br />
<p>1分で終わる<%= link_to "アンケートにご協力いただけませんか？","https://docs.google.com/forms/d/e/1FAIpQLSfjfErJ5DnhGchCoiX20bhvBCzn0tyPe72d9ca-gWLJ8pR4Ww/viewform?usp=sf_link"%></p>
</div>
<%
=begin
%>
<%= form_for(:question, url: question_create) do |f| %>
  <div class="row">
      <label>メールアドレス</label>
      <%= f.email_field :address, class: "form-control"%>
      <label>本文</label>
      <%= f.text_area :body, class: "form-control" %>
      <%= f.submit "送信", :class =>  "btn btn-primary form-control" %>
  </div>
<% end %>

<%
=end
%>

app/views/layouts/show_usage.html.erb
<div class="sample">
<%= image_tag "sample2.png" %>
</div>